### ISSUE TITLE
[bug][Knowhere2.0] RangeSearch is slower than version 1.3, and precision is not allowed

### ISSUE THREAD

**Issue by elstic** [milvus-io/knowhere#615]
ivfflat index latency:
![12f3df76-e590-4c97-93fd-fe76044bc60b](https://user-images.githubusercontent.com/48523564/210028868-201cbc16-57c0-4e36-ab11-097b1931b1b4.jpeg)

In version 1.3, nprobe is [1, 2, 4, 8, 16, 32, 64, 128, 256, 512] and the delay is
[0.5701, 1.0174, 2.0392, 3.8497, 7.4166, 12.7004, 23.1321, 45.3427, 91.5857, 186.9473]

**Comment by cydrain** [comment]
fixed by #618

**Comment by elstic** [comment]
After verification, the performance problem is solved, but the problem of precision of 0 still exists

**Comment by elstic** [comment]
When I use the new sift dataset the case passes and the precision is fine. But when I use the glove dataset, the case still does not pass


```
pytest test_ivf.py::TestIvf::test_ivf_recall --data_type glove
```

![image](https://user-images.githubusercontent.com/48523564/211773143-311261e9-676e-45a6-b290-c45d9821247b.png)

**Comment by elstic** [comment]
After verification and replacement of the sift-range dataset, the case passed.
